
version: '3.8'

services:
  pdfdownloader:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pdfdownloader
    volumes:
      - ./PDFDownload/ListFolder:/app/PDFDownload/ListFolder
      - ./PDFDownload/Output:/app/PDFDownload/Output
    ports:
      - 8080:8080

